require_relative '../lib/xdg/desktop'
require_relative '../lib/xdg/icon'
require_relative '../lib/app_data'
require_relative '../lib/ci_tooling'
require_relative '../lib/collectors'
require_relative '../lib/crawlers'
require_relative '../lib/fnmatchpattern'
require_relative '../lib/icon_fetcher'
require_relative '../lib/kde_project'
require_relative '../lib/thumbnailer'
require_relative '../lib/xml_languages'

require 'minitest/autorun'
require 'webmock/minitest'
require 'mocha/mini_test'
